# Generated by Django 5.2.4 on 2025-09-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocument',
            name='document_type',
            field=models.CharField(choices=[('balance', 'Бухгалтерский баланс'), ('profit_loss', 'Отчет о прибылях и убытках'), ('cash_flow', 'Отчет о движении денежных средств')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialratio',
            name='ratio_value',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
