# Generated by Django 5.2.4 on 2025-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_analysis', '0002_alter_financialdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialratio',
            name='ratio_value',
            field=models.FloatField(),
        ),
    ]
