# Generated by Django 5.2.6 on 2025-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='skills/pdf/'),
        ),
    ]
